### PR TITLE
Deployment script

### PR DESCRIPTION
**Pull request by manboy-eth**
Set up deployment scripts for testing etc.

### CODE REVIEW

**Review by auryn-macmillan — APPROVED** [review]
lgtm

**Comment by auryn-macmillan** [comment]
Could you rebase this on main, since there have been some changes.

**Comment by manboy-eth** [comment]
> Could you rebase this on main, since there have been some changes.

It seemed like it was only readme conflicts, so I manually merged it. 

However, I am not sure what is causing the error in the `yarn coverage` CI command (no errors locally): 
```
Error in plugin solidity-coverage: TypeError [ERR_INVALID_URL]: Invalid URL
```

**Comment by auryn-macmillan** [comment]
@manboy-eth, from what I can see, it's failing because the code-size of the contracts is too large.

**Comment by auryn-macmillan** [comment]
@manboy-eth, I'm looking into it now.
Can confirm that I do get this error when I run your branch locally.
```
Error in plugin solidity-coverage: TypeError [ERR_INVALID_URL]: Invalid URL
```

**Comment by auryn-macmillan** [comment]
@manboy-eth, removing forking from hardhat network fixed the invalid URL issue.

**Review by auryn-macmillan — APPROVED** [review]

**Pull request merged**
